API_KEY = "your_backend_api_key_here"
# Replace "your_backend_api_key_here" with an actual placeholder or a development key.
# This key is for authenticating with YOUR backend API, not directly for OpenAI/OpenRouter.

# Example if you also wanted to store OpenRouter key directly (though prompt implies backend handles this)
# OPENROUTER_API_KEY = "sk-or-..."
